// Mocks generated by Mockito 5.0.15 from annotations
// in mobile_challenge_2021/test/infrastructure/patient/patient_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dio/src/dio.dart' as _i2;
import 'package:mobile_challenge_2021/domain/core/request/patient_request.dart'
    as _i8;
import 'package:mobile_challenge_2021/domain/core/request/request_failure.dart'
    as _i6;
import 'package:mobile_challenge_2021/domain/patient/entities/patient.dart'
    as _i7;
import 'package:mobile_challenge_2021/domain/patient/i_patient_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [IPatientRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPropertyRepositoy extends _i1.Mock implements _i4.IPatientRepository {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  _i5.Future<_i3.Either<_i6.RequestFailure, List<_i7.Patient>>> getPatients(
          {_i8.PatientRequest? request}) =>
      (super.noSuchMethod(
              Invocation.method(#getPatients, [], {#request: request}),
              returnValue: Future<
                      _i3.Either<_i6.RequestFailure, List<_i7.Patient>>>.value(
                  _FakeEither_1<_i6.RequestFailure, List<_i7.Patient>>()))
          as _i5.Future<_i3.Either<_i6.RequestFailure, List<_i7.Patient>>>);
  @override
  String toString() => super.toString();
}
